# -*- coding: utf-8 -*-
"""crick1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ACuVOWTTuWqomtNgQymvY6dLTsoNDeb
"""

import pandas as pd
import json
import math
import numpy as np

# Load dataset (Replace this with your actual dataset file path)
df = pd.read_csv('sample_data.csv')

df.fillna(0, inplace=True)

df.head()

df1 = pd.DataFrame()

# Calculate Batting Metrics
df1["Strike Rate"] = (df["Total Runs"] / df["Balls Faced"]) * 100
df1["Batting Average"] = df["Total Runs"] / df["Innings Played"]
df1["Bowling Strike Rate"] = df["Overs Bowled"]*6 / df["Wickets"]
df1["Economy Rate"] = (df["Runs Conceded"] / df["Overs Bowled"]*6)*6

df1.replace([np.inf, -np.inf], 0, inplace=True)
df1.head()

def calculate_player_points(row):
    if row["Bowling Strike Rate"] == 0:
        if row["Economy Rate"] == 0:
            return (row["Strike Rate"] / 5 + row["Batting Average"] * 0.8)
        else:
            return (row["Strike Rate"] / 5 + row["Batting Average"] * 0.8) + (500 / row["Economy Rate"])
    else:
        return (row["Strike Rate"] / 5 + row["Batting Average"] * 0.8) - (500 / row["Bowling Strike Rate"] + 140 / row["Economy Rate"])

df1["Player Points"] = df1.apply(calculate_player_points, axis=1)

df1["Player Points"] = abs(df1["Player Points"])

df1["Value"] = round((9 * df1["Player Points"] + 100) * 1000 / 50000) * 50000

df1.replace([np.inf, -np.inf], 0, inplace=True)
df1.head(20)

df1.to_json("cricket_data.json", orient="records", indent=4)

print("JSON file saved successfully!")

import json

# Open and read the JSON file
with open("cricket_data.json", "r") as file:
    data = json.load(file)

# Print JSON data
print(json.dumps(data, indent=4))  # Pretty-print JSON